name: Release

# Run this workflow when a new tag is pushed
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cd app && make build

      # `github.ref_name` contains the tag (e.g., "v1.0.0")
      - name: Package binary
        run: |
          BINARY_NAME="amaru-pi"
          TARGET_DIR="app/target/aarch64-unknown-linux-gnu/release"
          ARCHIVE_NAME="${BINARY_NAME}-${{ github.ref_name }}-aarch64-unknown-linux-gnu.tar.gz"
          
          tar -czf "${ARCHIVE_NAME}" -C "${TARGET_DIR}" "${BINARY_NAME}"
          echo "ARCHIVE_PATH=${ARCHIVE_NAME}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE_PATH }}
          generate_release_notes: true
